# Generated by Django 6.0.2 on 2026-04-06 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_member_membership_plan_payment_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Utilities', 'Utilities'), ('Equipment', 'Equipment'), ('Salary', 'Salary'), ('Maintenance', 'Maintenance'), ('Marketing', 'Marketing'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='attedance',
            unique_together={('member', 'date')},
        ),
    ]
