# Generated by Django 4.2.23 on 2026-05-06 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_announcement_equipment_gymphoto_systemsetting_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Attedance',
            new_name='Attendance',
        ),
    ]
