# Generated by Django 4.2.23 on 2026-05-06 20:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_rename_attedance_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checkin_token',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
