# Generated by Django 4.2.23 on 2026-05-06 20:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_alter_member_checkin_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='checkin_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
