# Generated by Django 4.2.23 on 2026-05-14 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_alter_member_checkin_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_emoji', models.CharField(default='🏆', max_length=10)),
                ('requirement_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LibraryExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Strength', 'Strength'), ('Cardio', 'Cardio'), ('Flexibility', 'Flexibility'), ('HIIT', 'HIIT'), ('Other', 'Other')], max_length=50)),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=20)),
                ('description', models.TextField()),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('video_url', models.URLField(blank=True, help_text='Link to exercise video', null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='fitness_goal',
            field=models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Muscle Gain', 'Muscle Gain'), ('Endurance', 'Endurance'), ('Flexibility', 'Flexibility'), ('General Fitness', 'General Fitness')], default='General Fitness', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='medical_conditions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='URL to profile image', null=True),
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('photo_before', models.URLField(help_text="URL to 'before' or current progress photo")),
                ('photo_after', models.URLField(blank=True, help_text="URL to 'after' photo (optional)", null=True)),
                ('weight_at_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_photos', to='gym.member')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_on', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.achievement')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements_earned', to='gym.member')),
            ],
            options={
                'unique_together': {('member', 'achievement')},
            },
        ),
    ]
