# Generated by Django 4.2.23 on 2026-05-16 07:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0017_branch_announcement_branch_attendance_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainerassignment',
            name='requested_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trainerassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
