# Generated by Django 4.2.23 on 2026-05-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_trainerassignment_requested_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload profile image', null=True, upload_to='profile_pics/'),
        ),
    ]
