# Generated by Django 4.2.23 on 2026-05-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0019_alter_member_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gym_gallery/'),
        ),
        migrations.AlterField(
            model_name='gymphoto',
            name='url',
            field=models.URLField(blank=True, help_text='Direct link to the gym image (optional if image is uploaded)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='photo_after',
            field=models.ImageField(blank=True, help_text="Upload 'after' photo (optional)", null=True, upload_to='progress_photos/'),
        ),
        migrations.AlterField(
            model_name='progressphoto',
            name='photo_before',
            field=models.ImageField(help_text="Upload 'before' or current progress photo", upload_to='progress_photos/'),
        ),
        migrations.AlterField(
            model_name='trainerassignment',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='gym.trainer'),
        ),
    ]
