# Generated by Django 4.2.23 on 2026-06-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0020_gymphoto_image_alter_gymphoto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='branch_logos/'),
        ),
    ]
